Little changes
IvanFed3/HW_OOP_FI pull request #1
Opened 2022-11-29 17:28 UTC by IvanFed3

2022-12-02 13:30 UTC, shorodilov requested changes
Треба зробити зміни.
Метод `Product.get_total` треба переробити, щоб повертав число.
Метод `ShoppingCart.add` треба переробити, щоб додавав обʼєкт товару та кількість.
Метод `ShoppingCart.get_total` переробити відповідно до оновленої реалізвції та зробити щоб повертав число.

2022-12-02 13:42 UTC, IvanFed3 commented
А ці два класи повинні бути логічно пов'язані? Тобто перший, це номеклатура товарів і їх ціна, а другий це формування "закупок" згідно заданої номенклатури. І ціна для розрахунку суми корзини береться з аргументів класу Product. Правильно?

2022-12-02 14:17 UTC, IvanFed3 commented
> А ці два класи повинні бути логічно пов'язані? Тобто перший, це номеклатура товарів і їх ціна, а другий це формування "закупок" згідно заданої номенклатури. І ціна для розрахунку суми корзини береться з аргументів класу Product. Правильно?

2022-12-02 19:09 UTC, shorodilov commented
> А ці два класи повинні бути логічно пов'язані? Тобто перший, це номеклатура товарів і їх ціна, а другий це формування "закупок" згідно заданої номенклатури. І ціна для розрахунку суми корзини береться з аргументів класу Product. Правильно?

Так, все вірно

2022-12-02 19:19 UTC, shorodilov commented
Не треба створювати нові PR.
Одне завдання - один PR.

2022-12-02 19:20 UTC, shorodilov requested changes
Потребує змін

2022-12-02 19:20 UTC, shorodilov commented on hw_1.py
> +        return self.price*quantity
Не забувай про округлення, коли працюєш з числами з плаваючою точкою

2022-12-02 19:20 UTC, shorodilov commented on hw_1.py
>              sum_1 += i[1]*i[2]
Он вище у товару є метод для цього.

2022-12-02 19:20 UTC, shorodilov commented on hw_1.py
> +        return sum_1
І не забувай про округлення.

2022-12-02 19:20 UTC, shorodilov commented on hw_1.py
>      list = []
У одному списку буде доволі складно конктролювати значення.
Я розбив на 2 - для товарів та їх кількості.

2022-12-02 19:20 UTC, shorodilov commented on hw_1.py
> +        self.list.append([product.name, quantity, product.price])
Додавай обʼєкт, а не окремі значення його атрибутів.

2022-12-03 19:08 UTC, IvanFed3 commented
Поправ. Створив нову гілку. Не знаю, чи приходить Вам повідомлення.

2022-12-04 00:37 UTC, shorodilov commented
> Поправ. Створив нову гілку. Не знаю, чи приходить Вам повідомлення.

Я от таку картину бачу по гілках.
Якщо ти дійсно думаєш що я буду розбиратись яка з них "нова" - то це мимо каси :-).
![Uploading image.png…]()

2022-12-04 09:35 UTC, IvanFed3 commented
Блін...
4 рази передивився початок другого уроку, щоб зрозуміти наступний алгоритм:
нова гілка:
комміт
пул реквест
зауваження
оновлення
комміт
зауваження
оновлення
комміт
....
затведження
мердж 
Бо я спочатку зрозумів Ваші слова, як будь яке оновлення -> нова гілка.

2022-12-04 09:44 UTC, IvanFed3 commented
Переніс комміти з іншої гілки та видалив її.

2022-12-04 13:25 UTC, shorodilov approved these changes
Нормально.
Хоча можна б було скоротити назви атрибутів та поліпшити обход по кошику.
Можна залишити і виправити з наступними завданнями.

2022-12-04 13:25 UTC, shorodilov commented on hw_1.py
> +    list_shopping_cart_product = []
Дуже довгі назви, не зручно працювати.
Це не помилка, але ріже око.

2022-12-04 13:25 UTC, shorodilov commented on hw_1.py
> +        for i in range(len(self.list_shopping_cart_product)):
```python
for product, quantity in zip(self.list_shopping_cart_product, self.list_shopping_cart_quantity):
    sum_shopping_cart += product.get_total(quantity)
```

2022-12-04 21:02 UTC, shorodilov commented
Не кидайся в крайнощі.
Не треба створювати PR на кожне оновлення. Але й усе підряд кидати до одного PR не треба.
Якщо це 2-га робота - відкрий новий.

2022-12-04 21:58 UTC, shorodilov commented
> Блін... 4 рази передивився початок другого уроку, щоб зрозуміти наступний алгоритм: нова гілка: комміт пул реквест зауваження оновлення комміт зауваження оновлення комміт .... затведження мердж Бо я спочатку зрозумів Ваші слова, як будь яке оновлення -> нова гілка.

А чого для нового завдання не створив нову гілку та новий PR?
Яким чином тепер відрізнити де яка робота починається?
Відміни останній коміт на цій гілці, зроби мерж.
Потім нову гілку з потрібними комітами та новий PR.

2022-12-05 08:12 UTC, IvanFed3 commented
Ок)))

2022-12-05 08:13 UTC, merged