Homework 2
IvanFed3/HW_OOP_FI pull request #4
Opened 2022-12-05 08:26 UTC by IvanFed3

2022-12-05 11:56 UTC, shorodilov requested changes
Потребує допрацювання

2022-12-05 11:56 UTC, shorodilov commented on hw2.py
> +        return self.name
https://docs.python.org/3/reference/datamodel.html?highlight=__repr__#object.__repr__
За цієї реалізації тобі не потрібен `__str__`

2022-12-05 11:56 UTC, shorodilov commented on hw2.py
> +    def __add__(self, other):
Нащо тут порівняння?

2022-12-05 11:56 UTC, shorodilov commented on hw2.py
> +        if len(self.list_product) == 0:
Це жесть який заплутаний метод. Зроби по-нормальному.

1. Якщо товар у кошику
   1. Знайти індекс товару
   2. Змінити кільсть за індексом
3. Інакше
   1. Додати товар
   2. Додати кільсть

2022-12-05 11:56 UTC, shorodilov commented on hw2.py
> +        self.list_product = []
Не помилка, але...
`list_whatever` - погана назва. Тут ліпше використовувати множину та тайп хінтінг як наприклад:
```python
self.products: List[Product] = []
```

2022-12-05 11:56 UTC, shorodilov commented on hw2.py
> +    def __add__(self, other):
Те саме, що з додаванням товару. Тут дуже багато дій, які можна доволі легко спростити.
Перші 3 рядки (створення нового кошика та копіювання до нього поточного) - нормально.

2022-12-05 11:56 UTC, shorodilov commented on hw2.py
> +        for i in range(len(new_cart.list_product)):
От тут треба натомість дізнатись який тип того, що додаємо: `Product` чи `ShoppingCart`.
Якщо `Product` - додаємо до створеного кошика у кількості 1.
Якщо `ShoppingCart` - проходимось по корзині та додаємо відповідні товари та кількості.

2022-12-07 13:53 UTC, IvanFed3 commented on hw2.py
> +        if len(self.list_product) == 0:
Ахах, ок)

2022-12-07 13:53 UTC, IvanFed3 commented on hw2.py
> +    def __add__(self, other):
Щоб дізнатись чи товари одникові по назві та ціні. Якшо одинакові, то це один і той же.  ... Але видалив

2022-12-07 13:53 UTC, IvanFed3 commented on hw2.py
> +        self.list_product = []
Прикол, прикол...  Працює тільки self.products: list[Product] = [] і то, PyCharm свариться бо не може визначити тип змінної quantity, яка записується в список кількостей.

2022-12-07 13:56 UTC, IvanFed3 commented
В мене не виходить, додавання об'єкту класу Shopping  і об'єкту класу Product ((
Не можу зрозуміти чому в кінці виходить об'єкт типу NoneType.

2022-12-07 20:03 UTC, shorodilov commented
> В мене не виходить, додавання об'єкту класу Shopping  і об'єкту класу Product ((
> Не можу зрозуміти чому в кінці виходить об'єкт типу NoneType.

Надай будь ласка приклад, бо не розумію куди саме треба дивитись, а по усьому коду лазити не хочу:-)

2022-12-07 20:24 UTC, IvanFed3 commented
Класна у  Вас методика викладання. Поки формував запитання сам зрозумів помилку)))

2022-12-07 20:35 UTC, shorodilov commented
> Класна у  Вас методика викладання. Поки формував запитання сам зрозумів помилку)))

Та завжди будь ласка. Звертайся ще.
PS: до мене можна на "ти"

2022-12-07 20:49 UTC, shorodilov requested changes
Поки розв'яжи те, що по ревью, а там може я ще до чогось доколупаюсь.

2022-12-07 20:49 UTC, shorodilov commented on hw2.py
> +    def __add__(self, other):
От не поспішай щось робити, доки ти остаточно не впевнений у тому, що треба робити.
Спочатку - розуміння, потім - дія.
Бо я навіть зараз не можу згадати, яка тут була імплетація раніше.

2022-12-07 20:49 UTC, shorodilov commented on hw2.py
> +        self.unit = unit
```suggestion
```

2022-12-07 20:49 UTC, shorodilov commented on hw2.py
> +    def add_product(self, product, quantity: float = None) -> None:
Прибери дефолт для `quantity` - це порушення dependency injection

2022-12-07 20:49 UTC, shorodilov commented on hw2.py
> +    def __add__(self, other):
Так, ок...
Я хочу от щоб можна було робити от так:
```python
cart = cart_obj1 + cart_obj2
cart = cart_obj1 + product_obj
```

2022-12-07 21:09 UTC, IvanFed3 commented
Так, стоп, це застарілий код.

2022-12-07 21:15 UTC, IvanFed3 commented on hw2.py
> +    def add_product(self, product, quantity: float = None) -> None:
Ок. Як мені тоді зробити тоді присвоїти аргументу змінну, при умові що аргумент не буде заданий?

2022-12-07 21:17 UTC, IvanFed3 commented
cart = cart_obj1 + cart_obj2
cart = cart_obj1 + product_obj

На даний момент таке можна виконати.

2022-12-07 21:18 UTC, shorodilov commented
> cart = cart_obj1 + cart_obj2
> cart = cart_obj1 + product_obj
> 
> На даний момент таке можна виконати.

Добре, завтра ще разок передивлюсь.
Бо ревью почав ще вдень робити.

2022-12-09 10:07 UTC, shorodilov requested changes
Потребує виправлень

2022-12-09 10:07 UTC, shorodilov commented on hw2.py
> +    def add_product(self, product, quantity: float = None) -> None:
Ніяк.

2022-12-09 10:07 UTC, shorodilov commented on hw2.py
> +    def add_product(self, product, quantity: float = None) -> None:
Ага, я зрозумів...
`unit` - це одиня товару.
Ок, тоді нормально.

2022-12-09 10:07 UTC, shorodilov commented on hw2.py
> +        for i in self.products:
То зробити легше перевіркою
```suggestion
        if product in self.products:
            idx = self.products.index(product)
            self.quantities[idx] += quantity
```

2022-12-09 10:07 UTC, shorodilov commented on hw2.py
> +            for product_1, product_2 in zip(self.products, other.products):
От тут відбувається щось дуже не зрозуміле

2022-12-09 22:13 UTC, closed without merging

2022-12-09 22:48 UTC, IvanFed3 commented on hw2.py
> +        for i in self.products:
Так, може й простіше